query EventByUserId($userId: String!) {
  events(where: { user_id: { equals: $userId } }) {
    date
    id
    uuid
    type
    location_line_1
    location_line_2
    location_city
    postcode
    approximate_location
    start_time
    end_time
    custom_event_name
    high_demand
    urgency
  }
}
