name: Branch CI
on: pull_request

jobs:
  check-branch:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@v3

      - name: Install
        run: yarn install --frozen-lockfile
        shell: bash

      - name: Lint
        run: yarn run lint

      - name: Madge
        run: yarn run madge

      - name: Test
        run: yarn run test
