name: Branch CI
on: pull_request

jobs:
  check-branch:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node 20
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install
        run: yarn install --frozen-lockfile
        shell: bash

      - name: Lint
        run: yarn run lint

      - name: Madge
        run: yarn run madge

      - name: Test
        run: yarn run test
