name: Develop CI

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to AWS using SST
        uses: feast-it/tapas/deploy-sst@0.0.1
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          npm_token: ${{ secrets.NPM_TOKEN }}
          aws_region: "eu-west-1"
          service_name: "tahini-and-the-temple-of-doom"
          environment: "staging"
          node: "20"
